### ISSUE TITLE
Is this repo implement NIC_v1 or NIC_v2? 

### ISSUE THREAD

**Issue by shoveller86** [mybirth0407/Show-and-Tell-keras#2]
I have a question about this repo: Is this repo based the paper **<Show and Tell: Lessons learned from the 2015 MSCOCO Image Captioning Challenge> or  < Show and Tell: A Neural Image Caption Generator >?**

I found there are 2 paper about Show and Tell / NIC:

https://arxiv.org/pdf/1609.06647v1.pdf
《Show and Tell: Lessons learned from the 2015
MSCOCO Image Captioning Challenge》 -----------------------Implement NIC_v2
https://arxiv.org/pdf/1411.4555.pdf
《Show and Tell: A Neural Image Caption Generator》 -----------Implement NIC_v1

I noticed that the readme.md of this repo shows Show and Tell: A Neural Image Caption Generator , but I am not sure

**Comment by mybirth0407** [comment]
Sorry for the delayed response..

My repo is later (NIC_v1).
Thanks for your attention!
